### ISSUE TITLE
Rename `tdvp(solver, ...)` to something more generic

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensorTDVP.jl#29]
The generic function `tdvp(solver, ...)` that accepts a general solver may be confusingly named since it can encompass many different algorithms (TDVP, DMRG, DMRG-X, etc.).

@amilsted suggested an alternative name `sweeper`.

@emstoudenmire, @b-kloss any name suggestions? Some that come to mind are `local_update` (though that could be confused with the PEPS terminology), `sweeps_update`, `update_sites`, etc.

**Comment by amilsted** [comment]
`sweeping_update()`?

**Comment by emstoudenmire** [comment]
I would throw in the idea of `sweep_mps`. The name `sweeps_update` or `sweep_update` would be good to me as well.

**Comment by amilsted** [comment]
`sweep_update` or similar have the advantage that they generalize to not-MPS things like trees.
