### ISSUE TITLE
[bug] BoundsError

### ISSUE THREAD

**Issue by liangdonghu** [ITensor/ITensorTDVP.jl#30]
I encountered a bug in this library:
`ERROR: LoadError: BoundsError: attempt to access 32×32 Matrix{ComplexF64} at index [1:33, 1:33]
Stacktrace:
  [1] throw_boundserror(A::Matrix{ComplexF64}, I::Tuple{UnitRange{Int64}, UnitRange{Int64}})
    @ Base ./abstractarray.jl:691
  [2] checkbounds
    @ ./abstractarray.jl:656 [inlined]
  [3] _getindex
    @ ./multidimensional.jl:838 [inlined]
  [4] getindex(::Matrix{ComplexF64}, ::UnitRange{Int64}, ::UnitRange{Int64})
    @ Base ./abstractarray.jl:1218
  [5] applyexp(H::ProjMPO, tau::ComplexF64, x0::ITensor; kwargs::Base.Pairs{Symbol, Number, NTuple{4, Symbol}, NamedTuple{(:tol, :maxiter, :outputlevel, :current_time), Tuple{Float64, Int64, Int64, ComplexF64}}})
    @ ITensorTDVP /share/huliangdong/.julia/packages/ITensorTDVP/FHriC/src/applyexp.jl:84
...`

I think the allocated memory is not enough for the function `applyexp`:
https://github.com/ITensor/ITensorTDVP.jl/blob/2ca6a5516d26644ebb34b48f946f42a0488635b3/src/applyexp.jl#L37
but, the maximum index in this function will be `tmat_ext_size = tmar_size+2 = (iter+1)+2 <= maxiter+3` in some situation:
https://github.com/ITensor/ITensorTDVP.jl/blob/2ca6a5516d26644ebb34b48f946f42a0488635b3/src/applyexp.jl#L43-L44
https://github.com/ITensor/ITensorTDVP.jl/blob/2ca6a5516d26644ebb34b48f946f42a0488635b3/src/applyexp.jl#L83-L84

Therefore, the allocated matrix `bigTmat` should be
` 37   bigTmat = zeros(ElT, maxiter + 3, maxiter + 3)`

**Comment by mtfishman** [comment]
Thanks for the report @liangdonghu. Could you show a minimal runnable example that reproduces this error?

**Comment by mtfishman** [comment]
Thanks.

@emstoudenmire does the proposed fix make sense to you? Looks like we just need to change:
https://github.com/ITensor/ITensorTDVP.jl/blob/2ca6a5516d26644ebb34b48f946f42a0488635b3/src/applyexp.jl#L37
to:
```julia
  bigTmat = zeros(ElT, maxiter + 3, maxiter + 3)
```

**Comment by emstoudenmire** [comment]
Yes, it does make sense. When I ported that code, the main changes involved changing from 0 indexing in C++ to 1 indexing in Julia. And additionally, if some of these matrices are hypothetically a little bigger than needed it won't affect performance or correctness, so let's go with this change!

**Comment by mtfishman** [comment]
@liangdonghu would you mind making a pull request with the suggested changes? Thanks!

**Comment by awennersteen** [comment]
@mtfishman @emstoudenmire
If @liangdonghu is not able to submit a PR for this soon could one of you do it and release a new version of the package?

We're hitting this error too and it would be nice to have a fix upstream. 
The proposed fix did solve it for us :)

**Comment by liangdonghu** [comment]
Thank you for your reminder. I have submitted a new  PR for this bug.
