### ISSUE TITLE
Remove versions taking various argument orderings?

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensorTDVP.jl#35]
Currently there are some interfaces like the `tdvp` function which have wrappers that allow passing the arguments in a different order, for example:
```
tdvp(H,psi,t, ...)
```
instead of 
```
tdvp(H,t,psi,...)
```

Before finalizing this package, I would suggest we decide on a standard ordering for interfaces like this and remove the other orderings.

**Comment by mtfishman** [comment]
One reason I like the second one is that it is more similar to the equation `exp(Ht)|psi>` (in fact we could consider calling `tdvp` something like `exp` or `exponentiate`, in a future where there are multiple MPO-based time evolution backends).

**Comment by emstoudenmire** [comment]
Agreed that the second interface is nicer. I think we should just have one of them (since this package hasn't been released yet) so I'm happy with that one being the interface.
