### ISSUE TITLE
[ITensorTDVP][BUG] exponentiate from KrylovKit

### ISSUE THREAD

**Issue by kbidzhiev** [ITensor/ITensorTDVP.jl#38]
**Description of bug**

`
tdvp(
        H, dt * im, psi;
        nsite = 2, nsweeps = 1, reverse_step = true, normalize = true, outputlevel = 0, solver_krylovdim = 100,
        solver_backend = "exponentiate"
    )
` 
   doesn't work with 
`solver_backend = "exponentiate"`

**Expected output or behaviour**

ERROR: LoadError: Cannot serialize type KrylovKit.var"#eigselector##kw"

 eigselector(::Any, ::Type; issymmetric, ishermitian, krylovdim, maxiter, tol, orth, eager, verbosity) at /home/username/.julia/packages/KrylovKit/kWdb6/src/eigsolve/eigsolve.jl:205 got unsupported keyword arguments "current_time", "outputlevel"
 
 **Hot fix**
 To hot fix the problem I just replaced line 12 in ITensorTDVP/src/tdvp.jl  in function exponentiate_solver(; kwargs...) 
 `psi, info = exponentiate(H, t, psi0; solver_kwargs..., kws...)`
   by
`psi, info = exponentiate(H, t, psi0; solver_kwargs...) `

**Comment by mtfishman** [comment]
Yes I noticed that but didn't have time to fix it. Could you make a PR?

**Comment by kbidzhiev** [comment]
with my "hot fix" ?

**Comment by kbidzhiev** [comment]
with my 'hot fix' ?

**Comment by mtfishman** [comment]
Closed by #39.
