### ISSUE TITLE
Error with solver="exponentiate"

### ISSUE THREAD

**Issue by rborrelli** [ITensor/ITensorTDVP.jl#46]
Hi all,
I am running the test_tdvp.jl code and the  exponentiate solver backend throws the following error:

Basic TDVP: Error During Test at /home/lello/GitHub/ITensorTDVP.jl/test/test_tdvp.jl:33
  Test threw exception
  Expression: ψ1 ≈ tdvp(H, ψ0, -0.1im; nsweeps = 1, cutoff, nsite = 1, solver_backend = "exponentiate")
  MethodError: no method matching eigselector(::ProjMPO, ::Type{ComplexF64}; ishermitian=true, issymmetric=true, tol=1.0e-12, krylovdim=30, maxiter=100, verbosity=0, eager=true, current_time=0.0, outputlevel=0)
[....]
Basic TDVP: Error During Test at /home/lello/GitHub/ITensorTDVP.jl/test/test_tdvp.jl:47
  Test threw exception
  Expression: ψ2 ≈ tdvp(H, 0.1im, ψ1; nsweeps = 1, cutoff, solver_backend = "exponentiate")
  MethodError: no method matching eigselector(::ProjMPO, ::Type{ComplexF64}; ishermitian=true, issymmetric=true, tol=1.0e-12, krylovdim=30, maxiter=100, verbosity=0, eager=true, current_time=0.0, outputlevel=0)

How do I solve the problem? it seems to affect all the codes with the exponentiate backend.

**Comment by kbidzhiev** [comment]
I had similar issue. Please, have a look 

https://github.com/ITensor/ITensorTDVP.jl/issues/38

**Comment by rborrelli** [comment]
Hi, thanks for pointing this.

**Comment by mtfishman** [comment]
I just registered a new version so this should be fixed in ITensorTDVP 0.0.4.
