### ISSUE TITLE
Fix complex issue in applyexp solver

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensorTDVP.jl#49]
Possible issue with handling of complex numbers and real matrices in the applyexp TDVP solver, backtrace here:
https://itensor.discourse.group/t/tdvp-time-developing/563/5

**Comment by mtfishman** [comment]
The `applyexp` solver has been removed in ITensorTDVP v0.2 in favor of `KrlyovKit.exponentiate` so I'll close this.
