### ISSUE TITLE
No field "pm" in TimeDependentSum

### ISSUE THREAD

**Issue by linzhang1994** [ITensor/ITensorTDVP.jl#53]
In the following code, the ProjMPOSum type does not have the field "pm".

TimeDependentSum(f::Vector, H0::ProjMPOSum) = TimeDependentSum(f, H0.pm)

**Comment by mtfishman** [comment]
Thanks, this was changed to `ITensors.term(H0)` in https://github.com/ITensor/ITensors.jl/pull/1046.
