### ISSUE TITLE
Mention ITensorNetworks in the README?

### ISSUE THREAD

**Issue by amilsted** [ITensor/ITensorTDVP.jl#59]
Since ITensorNetworks can now do more general sweeping over tree tensor networks, should it perhaps be mentioned in the readme as a successor (assuming that is the plan)?

**Comment by mtfishman** [comment]
Yes, that's definitely the plan. It's a bit subtle since the TTN type in ITensorNetworks.jl doesn't have all of the same capabilities of the MPS/MPO types in ITensors.jl (yet) so it isn't quite ready for general users. But maybe good to give people a heads-up about what the plan is.

**Comment by mtfishman** [comment]
Closed by https://github.com/ITensor/ITensorTDVP.jl/commit/161209a7f8a6727f0b616626e4a9354f362b2c78.
